# https://www.netlify.com/docs/netlify-toml-reference/

[build]
    publish = "build"
    command = "npm run build"

[context.branch-deploy]
    command = "npm run build-dev"

[context.deploy-preview]
    command = "npm run build-dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200